name: med
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # UI & Icons
  google_fonts: ^4.0.0 
  font_awesome_flutter: ^10.4.0
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.3
  flutter_svg: 2.0.9
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1

  # State Management
  flutter_riverpod: ^2.6.1

  # Routing
  auto_route: ^8.1.4
  auto_route_generator: ^8.0.0

  # Firebase
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  google_sign_in: 

  # Storage & Preferences
  shared_preferences: ^2.0.15

  # Networking
  http: ^0.13.1
  url_launcher: ^6.2.2

  # Drawing & Images
  flutter_drawing_board: 
  image_picker: ^1.1.2

  # Chat & AI
  dash_chat_2: ^0.0.21
  dialog_flowtter: ^0.3.3
  flutter_gemini: ^3.0.0

  # Speech & Text
  speech_to_text: ^7.0.0
  intl: ^0.19.0

  # PDF & Printing
  pdf: ^3.10.7
  printing: ^5.11.0

  # Code Generation
  build_runner:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/icons/g_logo.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#ffffff"    # Background color for Android adaptive icons

flutter_native_splash:
  color: "#ffffff"                      # Background color
  image: assets/icons/app_icon.png       # Path to your splash image
  android: true
  ios: true
  fullscreen: true                      # Show the image fullscreen

  android_12:
    image: assets/icons/app_icon.png     # For Android 12+
    icon_background_color: "#ffffff"    # Background color for adaptive icons
